/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.*;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author culne
 */
public class AnadirNave extends javax.swing.JFrame {
    private Sistema modelo;
    private VentanaPrincipal ventana;
    private String pais;
    private String modeloNave;
    private boolean condicionesOptimas;
    private int capacidadMaxima;
    private int empuje;
    private int capTripulacion;
    private String cuerpoCeleste;
    private int empuje1;
    private int peso;
    
    /**
     * Creates new form AnadirLanzadera
     * @param unSistema
     * @param unaVentana
     */
    public AnadirNave(Sistema unSistema, VentanaPrincipal unaVentana) {
        this.modelo = unSistema;
        this.ventana = unaVentana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        txtCampoObligatorio = new javax.swing.JLabel();
        btnGroupPaises = new javax.swing.ButtonGroup();
        btnGroupCondiciones = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        btnGroupPaises1 = new javax.swing.ButtonGroup();
        btnGroupPaises2 = new javax.swing.ButtonGroup();
        btnGroupCondiciones1 = new javax.swing.ButtonGroup();
        btnGroupCondiciones2 = new javax.swing.ButtonGroup();
        panelLanzadera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioRusia = new javax.swing.JRadioButton();
        radioEEUU = new javax.swing.JRadioButton();
        radioChina = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioNo = new javax.swing.JRadioButton();
        radioSi = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        labelCampoObligatorio = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        spinnerFuerzaEmpuje = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spinnerCapTransporte = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelNoTripulada = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        radioRusia1 = new javax.swing.JRadioButton();
        radioEEUU1 = new javax.swing.JRadioButton();
        radioChina1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        radioNo1 = new javax.swing.JRadioButton();
        radioSi1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtModelo1 = new javax.swing.JTextField();
        labelCampoObligatorio1 = new javax.swing.JLabel();
        btnBorrar1 = new javax.swing.JButton();
        btnAnadir1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        spinnerFuerzaEmpuje1 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        txtCuerpoCeleste = new javax.swing.JTextField();
        panelTripulada = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        radioRusia2 = new javax.swing.JRadioButton();
        radioEEUU2 = new javax.swing.JRadioButton();
        radioChina2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radioNo2 = new javax.swing.JRadioButton();
        radioSi2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txtModelo2 = new javax.swing.JTextField();
        labelCampoObligatorio2 = new javax.swing.JLabel();
        btnBorrar2 = new javax.swing.JButton();
        btnAnadir2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        spinnerCapTripulacion = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        spinnerPeso = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jRadioButton3.setText("jRadioButton1");

        txtCampoObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        txtCampoObligatorio.setText("Campo obligatorio");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir lanzadera");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("País");

        btnGroupPaises.add(radioRusia);
        radioRusia.setSelected(true);
        radioRusia.setText("Rusia");
        radioRusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRusiaActionPerformed(evt);
            }
        });

        btnGroupPaises.add(radioEEUU);
        radioEEUU.setText("EEUU");
        radioEEUU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEEUUActionPerformed(evt);
            }
        });

        btnGroupPaises.add(radioChina);
        radioChina.setText("China");
        radioChina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChinaActionPerformed(evt);
            }
        });

        jLabel3.setText("Óptimas condiciones");

        btnGroupCondiciones.add(radioNo);
        radioNo.setSelected(true);
        radioNo.setText("No");
        radioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoActionPerformed(evt);
            }
        });

        btnGroupCondiciones.add(radioSi);
        radioSi.setText("Sí");
        radioSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        labelCampoObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelCampoObligatorio.setText("Campo obligatorio");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        spinnerFuerzaEmpuje.setModel(new javax.swing.SpinnerNumberModel(2500, 0, null, 100));

        jLabel6.setText("Fuerza empuje");

        jLabel5.setText("Toneladas");

        jLabel7.setText("Toneladas");

        spinnerCapTransporte.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 10));

        jLabel4.setText("Capacidad transporte");

        jLabel14.setText("Nave lanzadera");

        javax.swing.GroupLayout panelLanzaderaLayout = new javax.swing.GroupLayout(panelLanzadera);
        panelLanzadera.setLayout(panelLanzaderaLayout);
        panelLanzaderaLayout.setHorizontalGroup(
            panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanzaderaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampoObligatorio)
                    .addGroup(panelLanzaderaLayout.createSequentialGroup()
                        .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLanzaderaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(radioEEUU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioChina, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radioRusia))))
                        .addGap(70, 70, 70)
                        .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(panelLanzaderaLayout.createSequentialGroup()
                                .addComponent(spinnerCapTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLanzaderaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioSi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelLanzaderaLayout.createSequentialGroup()
                            .addComponent(btnBorrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnadir))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLanzaderaLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelLanzaderaLayout.createSequentialGroup()
                                    .addComponent(spinnerFuerzaEmpuje, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLanzaderaLayout.setVerticalGroup(
            panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanzaderaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioRusia)
                    .addComponent(spinnerCapTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(radioEEUU)
                .addGap(6, 6, 6)
                .addComponent(radioChina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNo)
                    .addComponent(spinnerFuerzaEmpuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(radioSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCampoObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelLanzaderaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnAnadir))
                .addGap(12, 12, 12))
        );

        labelCampoObligatorio.setVisible(false);

        Border blackline = BorderFactory.createLineBorder(Color.black);
        this.panelLanzadera.setBorder(blackline);

        jLabel8.setText("País");

        btnGroupPaises1.add(radioRusia1);
        radioRusia1.setSelected(true);
        radioRusia1.setText("Rusia");
        radioRusia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRusia1ActionPerformed(evt);
            }
        });

        btnGroupPaises1.add(radioEEUU1);
        radioEEUU1.setText("EEUU");
        radioEEUU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEEUU1ActionPerformed(evt);
            }
        });

        btnGroupPaises1.add(radioChina1);
        radioChina1.setText("China");
        radioChina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChina1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Óptimas condiciones");

        btnGroupCondiciones1.add(radioNo1);
        radioNo1.setSelected(true);
        radioNo1.setText("No");
        radioNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNo1ActionPerformed(evt);
            }
        });

        btnGroupCondiciones1.add(radioSi1);
        radioSi1.setText("Sí");
        radioSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSi1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Modelo");

        txtModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelo1ActionPerformed(evt);
            }
        });

        labelCampoObligatorio1.setForeground(new java.awt.Color(255, 0, 0));
        labelCampoObligatorio1.setText("Campo obligatorio");

        btnBorrar1.setText("Borrar");
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });

        btnAnadir1.setText("Añadir");
        btnAnadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Nave no tripulada");

        jLabel19.setText("Cuerpo celeste a estudiar");

        jLabel21.setText("Fuerza empuje");

        spinnerFuerzaEmpuje1.setModel(new javax.swing.SpinnerNumberModel(250, 0, null, 10));

        jLabel22.setText("kg");

        txtCuerpoCeleste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuerpoCelesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNoTripuladaLayout = new javax.swing.GroupLayout(panelNoTripulada);
        panelNoTripulada.setLayout(panelNoTripuladaLayout);
        panelNoTripuladaLayout.setHorizontalGroup(
            panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                        .addComponent(btnBorrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btnAnadir1))
                    .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                        .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCampoObligatorio1)
                            .addComponent(jLabel15)
                            .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                                .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(radioEEUU1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(radioChina1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(radioRusia1)
                                            .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(radioNo1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(radioSi1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                                        .addComponent(spinnerFuerzaEmpuje1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22))
                                    .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCuerpoCeleste, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelNoTripuladaLayout.setVerticalGroup(
            panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(radioRusia1)
                        .addGap(4, 4, 4)
                        .addComponent(radioEEUU1)
                        .addGap(6, 6, 6)
                        .addComponent(radioChina1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(radioNo1)
                        .addGap(2, 2, 2)
                        .addComponent(radioSi1))
                    .addGroup(panelNoTripuladaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCuerpoCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerFuerzaEmpuje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(txtModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelCampoObligatorio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelNoTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar1)
                    .addComponent(btnAnadir1))
                .addGap(12, 12, 12))
        );

        labelCampoObligatorio1.setVisible(false);

        this.panelNoTripulada.setBorder(blackline);

        jLabel11.setText("País");

        btnGroupPaises2.add(radioRusia2);
        radioRusia2.setSelected(true);
        radioRusia2.setText("Rusia");
        radioRusia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRusia2ActionPerformed(evt);
            }
        });

        btnGroupPaises2.add(radioEEUU2);
        radioEEUU2.setText("EEUU");
        radioEEUU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEEUU2ActionPerformed(evt);
            }
        });

        btnGroupPaises2.add(radioChina2);
        radioChina2.setText("China");
        radioChina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChina2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Óptimas condiciones");

        btnGroupCondiciones2.add(radioNo2);
        radioNo2.setSelected(true);
        radioNo2.setText("No");
        radioNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNo2ActionPerformed(evt);
            }
        });

        btnGroupCondiciones2.add(radioSi2);
        radioSi2.setText("Sí");
        radioSi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSi2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Modelo");

        txtModelo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelo2ActionPerformed(evt);
            }
        });

        labelCampoObligatorio2.setForeground(new java.awt.Color(255, 0, 0));
        labelCampoObligatorio2.setText("Campo obligatorio");

        btnBorrar2.setText("Borrar");
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });

        btnAnadir2.setText("Añadir");
        btnAnadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadir2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Nave tripulada");

        jLabel17.setText("Capacidad Tripulación");

        spinnerCapTripulacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel18.setText("Personas");

        spinnerPeso.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 10));

        jLabel23.setText("Peso");

        jLabel24.setText("Toneladas");

        javax.swing.GroupLayout panelTripuladaLayout = new javax.swing.GroupLayout(panelTripulada);
        panelTripulada.setLayout(panelTripuladaLayout);
        panelTripuladaLayout.setHorizontalGroup(
            panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTripuladaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTripuladaLayout.createSequentialGroup()
                        .addComponent(btnBorrar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btnAnadir2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTripuladaLayout.createSequentialGroup()
                        .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTripuladaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(radioEEUU2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioChina2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radioRusia2)
                                    .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(radioNo2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioSi2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCampoObligatorio2)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTripuladaLayout.createSequentialGroup()
                                .addComponent(spinnerCapTripulacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTripuladaLayout.createSequentialGroup()
                                .addComponent(spinnerPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addComponent(jLabel17))))
                .addContainerGap())
        );
        panelTripuladaLayout.setVerticalGroup(
            panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTripuladaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(5, 5, 5)
                .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioRusia2)
                    .addComponent(spinnerCapTripulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(3, 3, 3)
                .addComponent(radioEEUU2)
                .addGap(6, 6, 6)
                .addComponent(radioChina2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTripuladaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(radioNo2))
                    .addGroup(panelTripuladaLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(5, 5, 5)
                        .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addGap(0, 0, 0)
                .addComponent(radioSi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(txtModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelCampoObligatorio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelTripuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar2)
                    .addComponent(btnAnadir2))
                .addGap(12, 12, 12))
        );

        labelCampoObligatorio2.setVisible(false);

        this.panelTripulada.setBorder(blackline);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLanzadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTripulada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNoTripulada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLanzadera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        if(this.txtModelo.getText().equals("")){
            this.labelCampoObligatorio.setVisible(true);
        }else{

            modeloNave = txtModelo.getText();
            capacidadMaxima = (int) spinnerCapTransporte.getValue();
            empuje = (int) spinnerFuerzaEmpuje.getValue();

            if(radioRusia.isSelected()){
                pais = "Rusia";
            }else if(radioChina.isSelected()){
                pais = "China";
            }else if(radioEEUU.isSelected()){
                pais = "EEUU";
            }

            if(radioNo.isSelected()){
                condicionesOptimas = false;
            }
            
            boolean esta = false;
            for(int i=0; i<modelo.getListaNaves().size(); i++){
                Nave nave = modelo.getListaNaves().get(i);
                
                if(nave.getModelo().equals(this.modeloNave)){
                    esta = true;
                }
            }
            
            if(!esta){
                Lanzadera agregar = new Lanzadera(pais, modeloNave, condicionesOptimas, capacidadMaxima, empuje);
            modelo.agregarNave(agregar);
            }else{
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Modelo repetido");
                
            }
            ventana.actualizar();
            resetear();
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        resetear();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void radioRusia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRusia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRusia1ActionPerformed

    private void radioEEUU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEEUU1ActionPerformed
        this.pais = "EEUU";
    }//GEN-LAST:event_radioEEUU1ActionPerformed

    private void radioChina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChina1ActionPerformed
        this.pais = "China";
    }//GEN-LAST:event_radioChina1ActionPerformed

    private void radioNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNo1ActionPerformed

    private void radioSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSi1ActionPerformed
        this.condicionesOptimas = true;
    }//GEN-LAST:event_radioSi1ActionPerformed

    private void txtModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelo1ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        resetear();
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnAnadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir1ActionPerformed
        if(this.txtModelo1.getText().equals("")){
            this.labelCampoObligatorio1.setVisible(true);
        }else{

            this.modeloNave = txtModelo1.getText();
            this.cuerpoCeleste = txtCuerpoCeleste.getText();
            this.empuje1 = (int) spinnerFuerzaEmpuje1.getValue();
            
            if(this.cuerpoCeleste.length() == 0){
                this.cuerpoCeleste = "Sin especificar";
            }
            
            if(radioRusia1.isSelected()){
                pais = "Rusia";
            }else if(radioChina1.isSelected()){
                pais = "China";
            }else if(radioEEUU1.isSelected()){
                pais = "EEUU";
            }

            if(radioNo1.isSelected()){
                condicionesOptimas = false;
            }
            
            boolean esta = false;
            for(int i=0; i<modelo.getListaNaves().size(); i++){
                Nave nave = modelo.getListaNaves().get(i);
                
                if(nave.getModelo().equals(this.modeloNave)){
                    esta = true;
                }
            }
            
            if(!esta){
                NoTripulada agregar = new NoTripulada(pais, modeloNave, condicionesOptimas, empuje1, cuerpoCeleste);
                modelo.agregarNave(agregar);
            }else{
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Modelo repetido");
                
            }
            
            ventana.actualizar();
            resetear();
        }
    }//GEN-LAST:event_btnAnadir1ActionPerformed

    private void radioRusia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRusia2ActionPerformed

    }//GEN-LAST:event_radioRusia2ActionPerformed

    private void radioEEUU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEEUU2ActionPerformed

    }//GEN-LAST:event_radioEEUU2ActionPerformed

    private void radioChina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChina2ActionPerformed

    }//GEN-LAST:event_radioChina2ActionPerformed

    private void radioNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNo2ActionPerformed

    private void radioSi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSi2ActionPerformed

    }//GEN-LAST:event_radioSi2ActionPerformed

    private void txtModelo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelo2ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        resetear();
    }//GEN-LAST:event_btnBorrar2ActionPerformed

    private void btnAnadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadir2ActionPerformed
        if(this.txtModelo2.getText().equals("")){
            this.labelCampoObligatorio2.setVisible(true);
        }else{

            this.modeloNave = txtModelo2.getText();
            this.capTripulacion = (int) spinnerCapTripulacion.getValue();
            this.peso = (int) spinnerPeso.getValue();
            

            if(radioRusia2.isSelected()){
                pais = "Rusia";
            }else if(radioChina2.isSelected()){
                pais = "China";
            }else if(radioEEUU2.isSelected()){
                pais = "EEUU";
            }

            if(radioNo2.isSelected()){
                condicionesOptimas = false;
            }
            
            boolean esta = false;
            for(int i=0; i<modelo.getListaNaves().size(); i++){
                Nave nave = modelo.getListaNaves().get(i);
                
                if(nave.getModelo().equals(this.modeloNave)){
                    esta = true;
                }
            }
            
            if(!esta){
                Tripulada agregar = new Tripulada(peso, capTripulacion, pais, modeloNave, condicionesOptimas);
            modelo.agregarNave(agregar);
            }else{
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Modelo repetido");
                
            }
            ventana.actualizar();
            resetear();
        }
    }//GEN-LAST:event_btnAnadir2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ventana.setExisteVentanaAgregar(false);
    }//GEN-LAST:event_formWindowClosing

    private void txtCuerpoCelesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuerpoCelesteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuerpoCelesteActionPerformed

    private void radioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiActionPerformed
        condicionesOptimas = true;
    }//GEN-LAST:event_radioSiActionPerformed

    private void radioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoActionPerformed

    private void radioChinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChinaActionPerformed

    }//GEN-LAST:event_radioChinaActionPerformed

    private void radioEEUUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEEUUActionPerformed

    }//GEN-LAST:event_radioEEUUActionPerformed

    private void radioRusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRusiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRusiaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnAnadir1;
    private javax.swing.JButton btnAnadir2;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.ButtonGroup btnGroupCondiciones;
    private javax.swing.ButtonGroup btnGroupCondiciones1;
    private javax.swing.ButtonGroup btnGroupCondiciones2;
    private javax.swing.ButtonGroup btnGroupPaises;
    private javax.swing.ButtonGroup btnGroupPaises1;
    private javax.swing.ButtonGroup btnGroupPaises2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCampoObligatorio;
    private javax.swing.JLabel labelCampoObligatorio1;
    private javax.swing.JLabel labelCampoObligatorio2;
    private javax.swing.JPanel panelLanzadera;
    private javax.swing.JPanel panelNoTripulada;
    private javax.swing.JPanel panelTripulada;
    private javax.swing.JRadioButton radioChina;
    private javax.swing.JRadioButton radioChina1;
    private javax.swing.JRadioButton radioChina2;
    private javax.swing.JRadioButton radioEEUU;
    private javax.swing.JRadioButton radioEEUU1;
    private javax.swing.JRadioButton radioEEUU2;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioNo1;
    private javax.swing.JRadioButton radioNo2;
    private javax.swing.JRadioButton radioRusia;
    private javax.swing.JRadioButton radioRusia1;
    private javax.swing.JRadioButton radioRusia2;
    private javax.swing.JRadioButton radioSi;
    private javax.swing.JRadioButton radioSi1;
    private javax.swing.JRadioButton radioSi2;
    private javax.swing.JSpinner spinnerCapTransporte;
    private javax.swing.JSpinner spinnerCapTripulacion;
    private javax.swing.JSpinner spinnerFuerzaEmpuje;
    private javax.swing.JSpinner spinnerFuerzaEmpuje1;
    private javax.swing.JSpinner spinnerPeso;
    private javax.swing.JLabel txtCampoObligatorio;
    private javax.swing.JTextField txtCuerpoCeleste;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtModelo1;
    private javax.swing.JTextField txtModelo2;
    // End of variables declaration//GEN-END:variables

    public void resetear(){
        this.txtModelo.setText(null);
        this.radioRusia.setSelected(true);
        this.radioNo.setSelected(true);
        this.labelCampoObligatorio.setVisible(false);
        this.spinnerCapTransporte.setValue(100);
        this.spinnerFuerzaEmpuje.setValue(2500);
        
        this.txtModelo1.setText(null);
        this.radioRusia1.setSelected(true);
        this.radioNo1.setSelected(true);
        this.labelCampoObligatorio1.setVisible(false);
        this.txtCuerpoCeleste.setText("");
        this.spinnerFuerzaEmpuje1.setValue(250);
                
        this.txtModelo2.setText(null);
        this.radioRusia2.setSelected(true);
        this.radioNo2.setSelected(true);
        this.labelCampoObligatorio2.setVisible(false);
        this.spinnerCapTripulacion.setValue(0);
        spinnerPeso.setValue(100);
        
        
    }
}
